name: Makefile CI

on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main","master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 

    - name: Install dependencies
      run: make install 
 
